### ISSUE TITLE
 error: expected ')' before numeric constant  #define IPADDR_NONE         ((u32_t)0xffffffffUL)

### ISSUE THREAD

**Issue by MarkEvens** [espressif/arduino-esp32#4405]
ESP-IDF 4.0.1 with Arduino as components

suddenly i got above title error and don't understand why i am changing nothing in component files.

directory for this file is : $HOME/esp/esp-idf/components/lwip/lwip/src/include/lwip/ip4_addr.h:63:37

**Comment by turkysha** [comment]
You are missing ')' in that file ( in ip4_addr.h).

**Comment by MarkEvens** [comment]
@turkysha 
#define IPADDR_NONE         ((u32_t)0xffffffffUL)

this is the line 63 of ip4_addr.h what do you think that i have to change

**Comment by MarkEvens** [comment]
my problem solved by below issue
https://github.com/Microsoft/azure-iot-developer-kit/issues/169

**Comment by ameerhazo** [comment]
Hello @MarkEvens, I've stumbled upon the same error while trying to build an ESP-IDF component (coap) in my esp32 arduino/ESP-IDF mix project. Could you tell me how you resolved the issue? I'm asking this because the solution you linked is done on a different board. Thanks for the help.

**Comment by moefear85** [comment]
I face this too, although solved it by rearranging the order/locations of includes, since it appears different components are redefining the same symbols but in different ways. It might also be related to mixing C with C++ components. Usually this means extra code to safeguard has to be embedded. Unfortunately although now I'm following the same steps as I usually do, it's still not working. Does anybody know the exact systematic way to resolve this? In this case I believe the conflict is between Arduino and LwIP, as each defines IPADDR_NONE differently.

**Comment by awaters-meltin** [comment]
In case anyone else encounters this - the fix for me was to include the Arduino header first:
```
#include <WiFiUdp.h> // before lwip RE: https://github.com/espressif/arduino-esp32/issues/4405
#include <lwip/sockets.h>
```

**Comment by Magnatto** [comment]
> In case anyone else encounters this - the fix for me was to include the Arduino header first:
> 
> ```
> #include <WiFiUdp.h> // before lwip RE: https://github.com/espressif/arduino-esp32/issues/4405
> #include <lwip/sockets.h>
> ```

Thanks! Worked for me
