### ISSUE TITLE
ESP32 S3(FN8 chip or FR8 chip）use  partition table default_8MB.csv lead to reboot continuously（default.csv 4MB is fine)

### ISSUE THREAD

**Issue by Yeharold** [espressif/arduino-esp32#6646]
### Board

ESP32 S3

### Device Description

ESP32 S3(FN8 chip or FR8 chip） have 8MB Flash , DIY Board reference to hardware manul

### Hardware Configuration

[env:esp32s3]
platform = https://github.com/platformio/platform-espressif32.git
board = esp32-s3-devkitc-1
framework = arduino
upload_port = COM3
upload_speed = 921600
monitor_speed = 115200
board_build.partitions=default_8MB.csv
build_flags = 
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DCORE_DEBUG_LEVEL=5

### Version

latest master (checkout manually)

### IDE Name

PlatformIO

### Operating System

win10

### Flash frequency

80Mhz

### PSRAM enabled

yes

### Upload speed

921600

### Description

DIY board ESP32 S3(FN8 chip or FR8 chip） have 8MB Flash ,when I select  partition table default_8MB.csv, Build and upload .My device ESP32 S3(FN8 chip or FR8 chip） rebooting continuously.

### Sketch

```cpp
#include <Arduino.h>
#define PIN_RED    GPIO_NUM_5 // GIOP23
#define PIN_GREEN  GPIO_NUM_6  // GIOP22
#define PIN_BLUE   GPIO_NUM_7  // GIOP21
void setup() {
  pinMode(PIN_RED,   OUTPUT);
  pinMode(PIN_GREEN, OUTPUT);
  pinMode(PIN_BLUE,  OUTPUT);
  Serial.begin(115200);
}

void loop() {
  // color code #00C9CC (R = 0,   G = 201, B = 204)
  analogWrite(PIN_RED,   0);
  analogWrite(PIN_GREEN, 0);
  analogWrite(PIN_BLUE,  255);
  delay(1000); // keep the color 1 second
  // color code #F7788A (R = 247, G = 120, B = 138)
  analogWrite(PIN_RED,   255);
  analogWrite(PIN_GREEN, 0);
  analogWrite(PIN_BLUE,  0);
  delay(1000); // keep the color 1 second
  // color code #34A853 (R = 52,  G = 168, B = 83)
  analogWrite(PIN_RED,   0);
  analogWrite(PIN_GREEN, 255);
  analogWrite(PIN_BLUE,  0);
  delay(1000); // keep the color 1 second
  Serial.println("hello rgb");

}
```

### Debug Message

```plain
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403bb0ce
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x39c
load:0x403b6000,len:0x9a4
load:0x403ba000,len:0x2868
entry 0x403b61c0
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403bb0ce
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x39c
load:0x403b6000,len:0x9a4
load:0x403ba000,len:0x2868
entry 0x403b61c0
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
rst:0x3 (RTC_SW_SYS_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
Saved PC:0x403bb0ce
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd0108,len:0x39c
load:0x403b6000,len:0x9a4
load:0x403ba000,len:0x2868
entry 0x403b61c0
ESP-ROM:esp32s3-20210327
Build:Mar 27 2021
.....
```

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by me-no-dev** [comment]
N8 and R8 are different things. N8 means 8MB QSPI Flash, R8 means 8MB OPI PSRAM.
Try without `-DBOARD_HAS_PSRAM` and if it boots, I'll tell you what else to change.
This is for ESP32 Only! Remove please: `-mfix-esp32-psram-cache-issue`

**Comment by Jason2866** [comment]
Additional to what @me-no-dev said. Actual https://github.com/platformio/platform-espressif32.git does **not** yet support the S3.
If you want to try with platformio you can use my [fork](https://github.com/Jason2866/platform-espressif32). 
I use a ESP32-S3 with 8 MB flash and 8 MB PSRAM with actual Arduino master.
I does work fine!

**Comment by Jason2866** [comment]
Mandantory. Use esptool.py v3.3. Only this version has the flash size patch for the S3.

**Comment by Yeharold** [comment]
> N8 and R8 are different things. N8 means 8MB QSPI Flash, R8 means 8MB OPI PSRAM. Try without `-DBOARD_HAS_PSRAM` and if it boots, I'll tell you what else to change. This is for ESP32 Only! Remove please: `-mfix-esp32-psram-cache-issue`

thank u for your  answer，My boards N8 connect  to 8 MB PSRAM, R8 connect to 8MB FLASH. remove the config your give, the  issue is not fixed

**Comment by Yeharold** [comment]
> Additional to what @me-no-dev said. Actual https://github.com/platformio/platform-espressif32.git does **not** yet support the S3. If you want to try with platformio you can use my [fork](https://github.com/Jason2866/platform-espressif32). I use a ESP32-S3 with 8 MB flash and 8 MB PSRAM with actual Arduino master. I does work fine! (If you found the correct combination of the flash types)

thank you for your help so much, use[ your fork](https://github.com/Jason2866/platform-espressif32) solve my problem. divce work fine .

**Comment by Yeharold** [comment]
> Mandantory. Use esptool.py v3.3. Only this version has the flash size patch for the S3.

Follow your fork,  partition table error has been fixed. but I also have a problem with esptool.py v3.3, when the upload process start, esptool.py  connect my device time too short to config strapping pin(boot and rts),
![image](https://user-images.githubusercontent.com/24696000/165678714-cb9996c5-4293-48f3-88ae-f16822dd16c6.png)

**Comment by Jason2866** [comment]
Reduce upload speed. If this does not work try to put device manually in Upload mode.
If this is not working try a different USB cable and maybe a extern power supply.
This problem is not caused from the framework or Platformio

**Comment by UnexpectedMaker** [comment]
I think this is related to https://github.com/espressif/arduino-esp32/issues/6661
Folk using my boars are seeing it work with some flash sizes and not others, all using 2.0.3RC1

**Comment by Jason2866** [comment]
@UnexpectedMaker  No it is not related. S3 does compile with my Platformio fork and flashing via VSC is working too. The Arduino issue is probably that the reference `install.json` has no S3 entry.

**Comment by UnexpectedMaker** [comment]
> @UnexpectedMaker No it is not related. S3 does compile with my Platformio fork and flashing via VSC is working too. The Arduino issue is probably that the reference `install.json` has no S3 entry.

Ok, nps! Removing links other issue :)

**Comment by zekageri** [comment]
I have the same problem. I tought it was because of PIO.
[](https://github.com/platformio/platform-espressif32/issues/788)

With 4mb csv it is working fine ( except my data folder does not fit into the fs ) and if i use default_16mb.csv it will boot loop.

Iam using ESP32-WROVER-E ( 16mb flash 8mb external ram )

**Comment by zekageri** [comment]
I tried with [this fork](https://github.com/Jason2866/platform-espressif32) from @Jason2866 and i got a different boot loop serial output:

```C
rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:344
load:0x40078000,len:13328
=> 0x40078000: ?? ??:0
load:0x40080400,len:3488
=> 0x40080400: _init at ??:?
entry 0x400805d0
=> 0x400805d0: ?? ??:0
ets Jul 29 2019 12:21:46

rst:0x3 (SW_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:344
load:0x40078000,len:13328
=> 0x40078000: ?? ??:0
load:0x40080400,len:3488
=> 0x40080400: _init at ??:?
entry 0x400805d0
=> 0x400805d0: ?? ??:0
ets Jul 29 2019 12:21:46
```

**Comment by zekageri** [comment]
my problem was solved by replacing `board_build.flash_size = 16MB` with `board_upload.flash_size = 16MB`

here is my issue : https://github.com/platformio/platform-espressif32/issues/788

**Comment by SantiFerre** [comment]
> my problem was solved by replacing `board_build.flash_size = 16MB` with `board_upload.flash_size = 16MB`
> 
> here is my issue : [platformio/platform-espressif32#788](https://github.com/platformio/platform-espressif32/issues/788)

I had been looking for hours to see if it was a code problem when upgrading to a new version, but it turns out it was this. Thank you very much for your help.

**Comment by zekageri** [comment]
No problem. I also searched for days. xd

**Comment by richcj10** [comment]
I stopped the boot loop problem by adding the "board_upload.flash_size = 8MB"

But I am still getting file system  errors:

``
ESP-ROM:esp32s3-20210327                                           
Build:Mar 27 2021                                                   
rst:0x1 (POWERON),boot:0x3a (SPI_FAST_FLASH_BOOT)                     
SPIWP:0xee                                                    
Octal Flash Mode Enabled                                         
For OPI Flash, Use Default Flash Boot Mode                         
mode:SLOW_RD, clock div:1                                     
load:0x3fcd0108,len:0x78                                             
load:0x403b6000,len:0x95c                                              
load:0x403ba000,len:0x2718                                             
SHA-256 comparison failed:                                             
Calculated: fbadc2bc0d050432a3cff9776fbf2db407a913320099d747343aaea934f79933
Expected: 8abaa7e3d5266e80aa38747066b4dacdd0b0484dfe110af1596c38f9e39564ba
Attempting to boot anyway...                     
entry 0x403b61a8                                  
[    77][I][esp32-hal-psram.c:96] psramInit(): PSRAM enabled
[    80][E][esp32-hal-misc.•’ª’êþClientID = ESPPLC-223124
[   494][E][LittleFS.cpp:119] format(): Formatting LittleFS failed! Error: -1
[   494][E][LittleFS.cpp:94] begin(): Mounting LittleFS failed! Error: -1
LittleFS Mount Failed
``
Here is my .ini file:

[env:esp32dev]
;platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3.zip
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
;platform_packages = framework-arduinoespressif32 @ https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/829/framework-arduinoespressif32-v4.4.1-3010c4571f.tar.gz
board = esp32-s3-devkitc-1
board_upload.flash_size = 8MB
board_build.f_flash = 80000000L
board_build.partitions=default_8MB.csv
build_flags =
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=5
framework = arduino
upload_port = COM18
board_build.filesystem = littlefs
monitor_port = COM[5]
monitor_speed = 115200

If I enable "platform_packages " I get a lot of "fatal error: freertos/FreeRTOS.h: No such file or directory" errors. Weird

**Comment by Yeharold** [comment]
> [env:esp32s3]
> platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
> platform_packages = framework-arduinoespressif32 @ https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/829/framework-arduinoespressif32-v4.4.1-3010c4571f.tar.gz
> board = esp32-s3-devkitc-1
> framework = arduino
> upload_speed = 921600
> monitor_speed = 115200
> board_build.partitions=default_8MB.csv

**Comment by zekageri** [comment]
Have you tried only with:

```
platform = espressif32
framework   = arduino
```

in the ini?

**Comment by Yeharold** [comment]
> Have you tried only with:
> 
> ```
> platform = espressif32
> framework   = arduino
> ```
> 
> in the ini?

1 cd to your platform install dir: C:\Users\xxx\.platformio\platforms,and remove your espressif32 or espressif32@xx(delete the all espressif32 folders) platform
2 cd to your package install dir: C:\Users\xxx\.platformio\packages,remove all "framework-arduinoespressif32" or framework-arduinoespressif32@xx folder
3 open your exist project .ini
[env:esp32s3]
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
platform_packages = framework-arduinoespressif32 @ https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/829/framework-arduinoespressif32-v4.4.1-3010c4571f.tar.gz
board = esp32-s3-devkitc-1
framework = arduino

;this setting will reinstall espressif32 、framework-arduinoespressif32 and  related tools 

5 when installation finished:
![image](https://user-images.githubusercontent.com/24696000/169247314-e1c2e7b4-d178-4d8d-bf57-2f8268592855.png)

only with your setting will work

**Comment by Yeharold** [comment]
> > Mandantory. Use esptool.py v3.3. Only this version has the flash size patch for the S3.
> 
> Follow your fork, partition table error has been fixed. but I also have a problem with esptool.py v3.3, when the upload process start, esptool.py connect my device time too short to config strapping pin(boot and rts), ![image](https://user-images.githubusercontent.com/24696000/165678714-cb9996c5-4293-48f3-88ae-f16822dd16c6.png)

1 open this file
         C:\Users\xx\.platformio\packages\tool-esptoolpy\esptool.py
2 set more conntect try:![image](https://user-images.githubusercontent.com/24696000/169249952-a270be46-bf86-446a-8ca4-9ae80e99fe11.png)

**Comment by richcj10** [comment]
So clearing out my install directory helped. I don't get compile errors. But my FS will not init. 
Ini file:
`[env:esp32dev]
;platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3.zip
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
platform_packages = framework-arduinoespressif32 @ https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/829/framework-arduinoespressif32-v4.4.1-3010c4571f.tar.gz
board = esp32-s3-devkitc-1
board_upload.flash_size = 8MB
;board_build.f_flash = 80000000L
;board_build.partitions=default_8MB.csv
build_flags =
	-DBOARD_HAS_PSRAM
	-DCORE_DEBUG_LEVEL=5
framework = arduino
upload_port = COM18
board_build.filesystem = littlefs
monitor_port = COM[5]
monitor_speed = 115200
lib_deps = 
	knolleary/PubSubClient@^2.8.0
	https://github.com/husarnet/AsyncTCP.git
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson @ 6.17
	bodmer/TFT_eSPI@^2.4.61
	bitbank2/PNGdec@^1.0.1
	adafruit/Adafruit NeoPixel@^1.10.4`

This is for an ESP32-S3-WROOM-2

**Comment by henrygab** [comment]
I couldn't review the `.ini` due to its formatting.  If true for others, expand below for a reformatted version.

<details><summary>Formatted `.ini` section</summary><P/>

```ini
[env:esp32dev]
;platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3.zip
platform = https://github.com/tasmota/platform-espressif32/releases/download/v2.0.3rc1/platform-espressif32-2.0.3new.zip
platform_packages = framework-arduinoespressif32 @ https://github.com/Jason2866/esp32-arduino-lib-builder/releases/download/829/framework-arduinoespressif32-v4.4.1-3010c4571f.tar.gz
board = esp32-s3-devkitc-1
board_upload.flash_size = 8MB
;board_build.f_flash = 80000000L
;board_build.partitions=default_8MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=5
framework = arduino
upload_port = COM18
board_build.filesystem = littlefs
monitor_port = COM5
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8.0
    https://github.com/husarnet/AsyncTCP.git 
    https://github.com/me-no-dev/ESPAsyncWebServer.git bblanchon/ArduinoJson @ 6.17
    bodmer/TFT_eSPI@^2.4.61
    bitbank2/PNGdec@^1.0.1
    adafruit/Adafruit NeoPixel@^1.10.4`
```

</details>

NOTE: The original showed `monitor_port = COM[5]`; the square brackets seemed incorrect, so I removed them above.

**Comment by Jason2866** [comment]
Actual build (based on release core 2.0.3). I removed redundant not needed entrys and uncommented the 8MB partition scheme
```
[env:esp32dev]
platform = https://github.com/tasmota/platform-espressif32/releases/download/v.2.0.3/platform-espressif32-v.2.0.3.zip
board = esp32-s3-devkitc-1
board_build.partitions=default_8MB.csv
build_flags =
    -DCORE_DEBUG_LEVEL=5
framework = arduino
upload_port = COM18
board_build.filesystem = littlefs
monitor_port = COM5
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8.0
    https://github.com/husarnet/AsyncTCP.git 
    https://github.com/me-no-dev/ESPAsyncWebServer.git bblanchon/ArduinoJson @ 6.17
    bodmer/TFT_eSPI@^2.4.61
    bitbank2/PNGdec@^1.0.1
    adafruit/Adafruit NeoPixel@^1.10.4`
```

**Comment by richcj10** [comment]
Thanks, I will try that. I will get back to you tonight.

**Comment by richcj10** [comment]
I am getting this error now:

`Warning! Ignore unknown configuration option `framework` in section [platformio]
Warning! Ignore unknown configuration option `platform` in section [platformio]
Processing esp32-s3dev (board: esp32-s3-devkitc-1)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Error: Please specify platform for 'esp32-s3dev' environment
The terminal process "C:\Users\richc\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.`

**Comment by Jason2866** [comment]
Ahh yes. Mistake. Should look like
```
[common]
framework = arduino
platform = https://github.com/tasmota/platform-espressif32/releases/download/v.2.0.3/platform-espressif32-v.2.0.3.zip

[env:esp32-s3dev]
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions=default_8MB.csv
build_flags =
    -DCORE_DEBUG_LEVEL=5
upload_port = COM18
monitor_port = COM5
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8.0
    https://github.com/husarnet/AsyncTCP.git 
    https://github.com/me-no-dev/ESPAsyncWebServer.git bblanchon/ArduinoJson @ 6.17
    bodmer/TFT_eSPI@^2.4.61
    bitbank2/PNGdec@^1.0.1
    adafruit/Adafruit NeoPixel@^1.10.4`
```

**Comment by richcj10** [comment]
I am still getting an error "no platform selected" 

Thoughts?

**Comment by richcj10** [comment]
I also tried updating PIO since the latest "beta" fix is about compile flags.  Still not working. 
I did try this:

'
[env:esp32-s3dev]
framework = arduino
platform = https://github.com/tasmota/platform-espressif32/releases/download/v.2.0.3/platform-espressif32-v.2.0.3.zip
board = esp32-s3-devkitc-1
board_build.filesystem = littlefs
board_build.partitions=default_8MB.csv
build_flags =
    -DCORE_DEBUG_LEVEL=5
upload_port = COM18
monitor_port = COM5
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8.0
    https://github.com/husarnet/AsyncTCP.git 
    https://github.com/me-no-dev/ESPAsyncWebServer.git bblanchon/ArduinoJson @ 6.17
    bodmer/TFT_eSPI@^2.4.61
    bitbank2/PNGdec@^1.0.1
    adafruit/Adafruit NeoPixel@^1.10.4
'
If i try flash mode OPI / 8MB / Partition 8MB / PSRAM = OPI PSRAM, it works in Arduino IDE. I have a FS. I don't think I have a OTA update partition, but I am not to worried about that right now.

**Comment by Jason2866** [comment]
@richcj10 I think it is the wrong place for your problem, since Arduino IDE works for you?
Imho problems with Platformio should be addressed in [Platformio](https://github.com/platformio/platform-espressif32/issues) github.

**Comment by me-no-dev** [comment]
@richcj10 you probably need `build.arduino.memory_type = opi_opi`

**Comment by Jason2866** [comment]
Make a boards.json for platformio. Create a folder `boards` in root of your project
Name the json like `esp32s3_opi.json` and save in folder `boards`
You use your own board as usual, so `boards = esp32s3_opi`
The json
```
{
  "build": {
    "arduino":{
      "ldscript": "esp32s3_out.ld",
      "memory_type": "opi_opi"
    },
    "core": "esp32",
    "extra_flags": "-DBOARD_HAS_PSRAM -DARDUINO_USB_MODE=0 -DARDUINO_USB_CDC_ON_BOOT=0 -DARDUINO_USB_MSC_ON_BOOT=0 -DARDUINO_USB_DFU_ON_BOOT=0",
    "f_cpu": "240000000L",
    "f_flash": "80000000L",
    "flash_mode": "dio",
    "mcu": "esp32s3",
    "variant": "esp32s3",
    "partitions": "default_8MB.csv"
  },
  "connectivity": [
    "wifi",
    "bluetooth",
    "ethernet"
  ],
  "debug": {
    "openocd_target": "esp32s3.cfg"
  },
  "frameworks": [
    "espidf",
    "arduino"
  ],
  "name": "Espressif Generic ESP32-S3 8M OPI Flash, 8MB OPI PSRAM",
  "upload": {
    "flash_size": "8MB",
    "maximum_ram_size": 327680,
    "maximum_size": 8388608,
    "require_upload_port": true,
    "speed": 460800
  },
  "url": "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/",
  "vendor": "Espressif"
}
```

**Comment by Jason2866** [comment]
Maybe you have to change the `"flash_mode": "dio",` to `"flash_mode": "opi",` too
I have no S3 with OPI so i cant test

**Comment by Jason2866** [comment]
@me-no-dev  It is like i thought in https://github.com/espressif/arduino-esp32/discussions/6426

**Comment by richcj10** [comment]
Thanks for the help!  It still is boot looping at the bootloader. 

I did notice this that I thought was weird: 
`Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0x3980c2, SizeID=0x39), defaulting to 4MB`

**Comment by richcj10** [comment]
I did a diff of the platformio-build-esp32s3.py and found these differences: 

"-u", "include_esp_phy_override",
Arduino uses ("IDF_VER", '\\"v4.4.1-1-gb8050b365e\\"'), vs ("IDF_VER", '\\"v4.4-367-gc29343eb94\\"'),

Also esptool.py is 100% match. Weird.

**Comment by code-is-art** [comment]
I have an esp32-s3-wroom-1 M0N8R8 which I think is just the N8R8 version. Not sure what the M0 is for. In any case I had one hell of a time figuring out how to get psram working on it in platformio. Using ps_malloc would cause it to go into a continuous reboot look. This is what I figured out after many hours of searching and trial and error.
My board profile...
```json
{
    "build": {
      "arduino":{
        "ldscript": "esp32s3_out.ld",
        "memory_type": "qspi_opi"
      },
      "core": "esp32",
      "extra_flags": "-DBOARD_HAS_PSRAM",
      "f_cpu": "240000000L",
      "f_flash": "80000000L",
      "flash_mode": "dio",
      "mcu": "esp32s3",
      "variant": "esp32s3",
      "partitions": "partitions/default_8MB.csv"
    },
    "connectivity": [
      "wifi"
    ],
    "debug": {
      "openocd_target": "esp32s3.cfg"
    },
    "frameworks": [
      "arduino",
      "espidf"
    ],
    "name": "Espressif ESP32-S3-DevKitC-1 N8R8 8MB QSPI FLASH 8MB OPI PSRAM",
    "upload": {
      "flash_size": "8MB",
      "maximum_ram_size": 524288,
      "maximum_size": 8388608,
      "require_upload_port": true,
      "speed": 460800
    },
    "url": "https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html",
    "vendor": "Espressif"
  }
```
Notice the "memory_type": "qspi_opi". This was the only thing that worked for this board. NOT opi_opi, qspi_qspi, qspi or opi_qspi. Tried them all without success. [Notice here the memory designation.](https://docs.espressif.com/projects/esp-idf/en/latest/esp32s3/hw-reference/esp32s3/user-guide-devkitc-1.html)  Flash: 8 MB QD, PSRAM: 8 MB OT. I was able to verify that all Flash and PSRAM is working after using this board definition with the following code.
```cpp
#include <Arduino.h>

void setup() {
  log_d("Total heap: %d", ESP.getHeapSize());
  log_d("Free heap: %d", ESP.getFreeHeap());
  log_d("Total PSRAM: %d", ESP.getPsramSize());
  log_d("Free PSRAM: %d", ESP.getFreePsram());
}

void loop() {}
```
As far as monitoring this is what I got on my ini file. Works for me though there might be better options..
```
monitor_speed = 115200
monitor_rts = 0
monitor_dtr = 0
```

**Comment by richcj10** [comment]
@code-is-art Would you share your .ini file? I am still having issues. Did your ESP32 upload state this: "Warning: Could not auto-detect Flash size (FlashID=0x3980c2, SizeID=0x39), defaulting to 4MB"?

**Comment by Jason2866** [comment]
@richcj10 when this `defaulting to 4MB` happens you will end in a bootloop.
There is nothing else needed in a platformio.ini file. The above boards.json has anything needed defined. Heads up. In a standard setup this `"partitions": "partitions/default_8MB.csv"` needs to be changed to `"partitions": "default_8MB.csv"`

**Comment by BenjaminLovelady** [comment]
> Additional to what @me-no-dev said. Actual https://github.com/platformio/platform-espressif32.git does **not** yet support the S3. If you want to try with platformio you can use my [fork](https://github.com/Jason2866/platform-espressif32). I use a ESP32-S3 with 8 MB flash and 8 MB PSRAM with actual Arduino master. I does work fine! (If you found the correct combination of the flash types)

Jan 2023, and Jason's fork fixed my issues. There's got to still be something in there that desperately needs a pull request to master. (I was having it fail on format: "esp32s3 /components/esp_littlefs/src/littlefs/lfs.c:1790:debug: Bad block at 0x0")

**Comment by Parsaabasi** [comment]
Hello, 

Due to the overwhelming volume of issues currently being addressed, we have decided to close the previously received tickets. If you still require assistance or if the issue persists, please don't hesitate to reopen the ticket.

Thanks.
